### ISSUE TITLE
Feature Request: support dot repeat

### ISSUE THREAD

**Issue by XXiaoA** [CKolkey/ts-node-action#11]
According to my test, `require("ts-node-action").node_action()` doesn't support  dot `.` repeat now.

**Comment by CKolkey** [comment]
Good point! I'll add that.

**Comment by CKolkey** [comment]
Could you check out https://github.com/CKolkey/ts-node-action/pull/14 and let me know if it behaves how you expect? I'll admit, I don't really see the point of this feature, but I have the action bound to `K`, so repeating it with `.` is a bit pointless, since my finger is already on `K`. I'm curious what your use case is, if you don't mind sharing :)

**Comment by XXiaoA** [comment]
Ummm. it still doesn't work for me.

**Comment by CKolkey** [comment]
Ah, ok. Do you have `tpope/vim-repeat` installed?

**Comment by XXiaoA** [comment]
yes

**Comment by CKolkey** [comment]
Hi! I tried to recreate the issue by cloning your nvim config and trying out that branch, but it works perfectly there too. I'll merge this, but feel free to open an issue if you're still having problems after :)

**Comment by CKolkey** [comment]
Thanks for the suggestion!

**Comment by XXiaoA** [comment]
Okay,  thanks for ur nice job!
