### ISSUE TITLE
Lua toggle_multiline mulfunction

### ISSUE THREAD

**Issue by Bekaboo** [CKolkey/ts-node-action#6]
Currently toggle_multiline for Lua cannot wrap a table in one line:

https://user-images.githubusercontent.com/76579810/211409032-8bf93d91-88c1-40bf-b5b8-bf066acc4467.mp4

**Comment by CKolkey** [comment]
So I can _kinda_ reproduce this. The node-action doesn't add a linebreak, but `lua-language-server` will do it when it formats the buffer, since the line is now too long. Can you see if the issue still happens after running `:LspStop` ?

https://user-images.githubusercontent.com/7228095/211410570-55faa0cd-8fe9-4bb1-a358-4b9d0c8edcd1.mov

**Comment by Bekaboo** [comment]
Thanks for your reply, after `:LspStop` the table can be wrapped into one line, so it is an issue with LSP.

**Comment by CKolkey** [comment]
Ahh, ok, it's because you are overwriting `==` with  `{ 'n', '==', '<cmd>lua vim.lsp.buf.format()<CR>' },` and I use it here https://github.com/CKolkey/ts-node-action/blob/master/lua/ts-node-action/init.lua#L33 to indent the updated lines.

**Comment by Bekaboo** [comment]
Exactly. I would suggest using `normal!` to force using the defult mapling.
